/* Oryveta Soft Modern MVP. No third-party client scripts; server owns permissions. */
'use strict';
const $ = (selector) => document.querySelector(selector);
const icon = (name, cls = '') => `<svg class="icon ${cls}" aria-hidden="true"><use href="#i-${name}"></use></svg>`;
const esc = (value) => String(value ?? '').replace(/[&<>"']/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state = {user:null,csrf:'',projects:[],overview:{},activity:[],current:'home',project:null,importMode:'github',modelStatus:'disabled',modelName:null,aiBudget:null,preview:false};
const titles = {home:'Overview',new:'Start New',evolve:'Evolve',projects:'Projects',activity:'Activity',detail:'Project'};
function toast(message, error = false){const box=$('#toast');box.textContent=message;box.className=`toast${error?' error':''}`;clearTimeout(toast.timer);toast.timer=setTimeout(()=>box.classList.add('hidden'),4700)}
async function api(path,{method='GET',data,headers={},body}={}){
 const opts={method,credentials:'same-origin',headers:{...headers}};
 if(method!=='GET'&&state.csrf)opts.headers['X-Oryveta-CSRF']=state.csrf;
 if(data!==undefined){opts.headers['Content-Type']='application/json';opts.body=JSON.stringify(data)}
 if(body!==undefined)opts.body=body;
 const response=await fetch(path,opts);
 if(!response.ok){let message=`Request failed (${response.status})`;try{const issue=await response.json();message=typeof issue.detail==='string'?issue.detail:message}catch{}throw new Error(message)}
 if(response.status===204)return null;
 const content=response.headers.get('content-type')||'';
 return content.includes('application/json')?response.json():response;
}
const pageHeader=(eyebrow,title,description)=>`<div class="page-header"><span class="eyebrow">${eyebrow}</span><h1>${title}</h1><p>${description}</p></div>`;
const empty=(title,body)=>`<div class="empty"><div class="empty-icon">${icon('folder')}</div><b>${title}</b><br>${body}</div>`;
function projectRows(limit=100){const rows=state.projects.slice(0,limit);return rows.length?rows.map(p=>`<div class="project-row"><div class="p-icon">${icon(p.origin==='import'?'git':'folder')}</div><div class="project-text"><b>${esc(p.name)}</b><small>${p.origin==='import'?'Imported repository':'Created project'} · ${esc(p.status)}</small></div><button data-project="${esc(p.id)}" aria-label="View ${esc(p.name)}">${icon('arrow')}</button></div>`).join(''):empty('No projects yet','Build a starter or import a codebase to begin.');}
function activityRows(limit=100){const items=state.activity.slice(0,limit);return items.length?items.map(a=>`<div class="activity-row"><span class="action-icon" style="margin:0;height:31px;width:31px">${icon('activity')}</span><div class="project-text"><b>${esc(a.detail)}</b><small>${esc(a.kind)} · ${new Date(a.created_at*1000).toLocaleString()}</small></div></div>`).join(''):empty('A clear slate','Your engineering activity will appear here.');}
const guide=(title,steps)=>`<aside class="card aside-guide"><h3 class="guide-header">${title}</h3>${steps.map((s,i)=>`<div class="guide-step"><span class="step-no">0${i+1}</span><div><b>${s[0]}</b><p>${s[1]}</p></div></div>`).join('')}<div class="divider"></div><div class="notice">${icon('shield')} Every meaningful change should be supported by tests and review evidence.</div></aside>`;
const pages={
 home(){const o=state.overview;return `${pageHeader('YOUR WORKSPACE','Good software gets better.','Two ways to make progress. Build a new product or evolve what you already have.')}
 ${state.preview?'<div class="notice notice-warning">This is the public UI preview. Live GitHub login, projects and Ollama inference require the self-hosted API. Explore the layout below; no operations will be saved.</div>':''}
 <div class="kpi-grid">${[['Projects',o.projects||0,'In your workspace'],['Active jobs',o.active_jobs||0,'Background work'],['Evaluations',o.verified_runs||0,'Completed benchmark runs'],['Activity',state.activity.length,'Recent events']].map(k=>`<div class="card kpi"><div class="kpi-label">${k[0]}</div><div class="kpi-val">${k[1]}</div><div class="kpi-meta">${k[2]}</div></div>`).join('')}</div>
 <div class="section-title"><h2>Where would you like to begin?</h2><span class="pill">Your next move</span></div>
 <div class="action-grid"><button class="action-card" data-page="new"><span class="action-icon">${icon('sparkles')}</span><h3>Start New</h3><p>Describe a product, choose a stack and create a runnable repository with tests and CI. Keep shaping it from there.</p><div class="action-arrow">${icon('arrow')}</div></button><button class="action-card" data-page="evolve"><span class="action-icon alt">${icon('git')}</span><h3>Evolve Existing</h3><p>Import a repository to examine bugs, dead-code candidates, security smells and modernization opportunities.</p><div class="action-arrow">${icon('arrow')}</div></button></div>
 <section class="card panel ai-panel" style="margin-top:24px"><div class="section-title"><h2>Local AI assistant</h2><span class="pill" id="ai-status">${esc(state.modelStatus)}${state.modelName?' · '+esc(state.modelName):''}</span></div>
 <p class="form-intro">Open-weight Ollama inference runs on your own computer or self-hosted server. Suggestions are unverified and never execute code.</p>
 <form id="ai-form"><div class="field"><label for="ai-prompt">Ask the local model</label><textarea id="ai-prompt" name="prompt" maxlength="4096" required placeholder="Suggest a test plan for my Python API..." ${state.modelStatus==='ready'?'':'disabled'}></textarea></div>
 <div class="tag-row"><button class="btn" id="ai-submit" type="submit" ${state.modelStatus==='ready'?'':'disabled'}>${icon('sparkles')} Generate text</button><button type="button" class="btn btn-outline" data-refresh-ai>Check model</button><span class="field-hint" id="ai-budget">${state.aiBudget?esc(state.aiBudget.remaining_tokens)+' tokens left today':'20,000 token daily allowance'}</span></div></form>
 <pre class="json-preview hidden" id="ai-output" role="status" aria-live="polite"></pre>
 <p class="field-hint" style="margin-top:13px">Model disabled or unavailable? See docs/MODEL-GATEWAY.md for local setup. The Vercel site is a UI preview only.</p></section>
 <div class="content-grid"><section class="card panel"><div class="section-title"><h2>Recent projects</h2><button data-page="projects" class="text-link">View all →</button></div>${projectRows(4)}</section><section class="card panel"><div class="section-title"><h2>Recent activity</h2><button data-page="activity" class="text-link">View all →</button></div>${activityRows(4)}</section></div>`},
 new(){return `${pageHeader('BUILD SOMETHING NEW','From idea to repository.','Describe what you need. Oryveta prepares a runnable, testable project foundation.')}
 <div class="form-shell"><section class="card form-card"><h2>Tell us what you're building</h2><p class="form-intro">Start with a clear idea. Your starter repository includes source code, documentation and verification tooling.</p><form id="new-form"><div class="field"><label for="project-name">Project name</label><input id="project-name" name="name" maxlength="90" minlength="2" placeholder="e.g. Client Portal" required></div><div class="field"><label for="project-type">Project foundation</label><select id="project-type" name="blueprint"><option value="python-api">Backend service · FastAPI</option><option value="web-app">Web application · HTML / CSS / JavaScript</option><option value="ai-service">AI service · FastAPI + model adapter</option></select></div><div class="field"><label for="project-brief">What should it do?</label><textarea id="project-brief" name="brief" required minlength="10" maxlength="2500" placeholder="Describe users, core features, constraints and what success looks like..."></textarea><span class="field-hint">Your brief is saved in the repository. Custom implementation is a later engineering step.</span></div><button type="submit" class="btn" id="create-button">${icon('sparkles')} Create starter repository ${icon('arrow')}</button></form></section>${guide('Your build journey',[['Define','Capture the intended application and required outcomes.'],['Generate','Create a portable source repository with baseline tests.'],['Verify','Review, implement project-specific behavior and validate it.'],['Deliver','Export the repo. GitHub publishing and cloud deployment are future integrations.']])}</div>`},
 evolve(){return `${pageHeader('IMPROVE WHAT EXISTS','Great software never stands still.','Understand your codebase, uncover risks and make evidence-backed modernization decisions.')}
 <div class="form-shell"><section class="card form-card"><h2>Import a repository</h2><p class="form-intro">Bring in a repository snapshot. Oryveta will analyze source code without running untrusted repository scripts.</p><div class="tab-row"><button data-tab="github" class="tab ${state.importMode==='github'?'active':''}">GitHub URL</button><button data-tab="zip" class="tab ${state.importMode==='zip'?'active':''}">Upload ZIP</button></div>
 ${state.importMode==='github'?`<form id="github-import"><div class="field"><label for="repository-url">Public GitHub repository URL</label><input id="repository-url" required type="url" placeholder="https://github.com/owner/repository" pattern="https://github\\.com/[^/]+/[^/]+/?"><span class="field-hint">Public repositories only in this MVP. Private imports will use an installed GitHub App.</span></div><button class="btn" id="import-button" type="submit">${icon('git')} Import & analyze ${icon('arrow')}</button></form>`:`<form id="zip-import"><div class="field"><label for="zip-name">Project name</label><input id="zip-name" required placeholder="My existing service"></div><div class="upload-zone">${icon('download')}<p>Choose a ZIP archive containing your repository snapshot.</p><input id="zip-file" type="file" accept=".zip,application/zip" required><p>Maximum 12 MB compressed; 32 MB extracted.</p></div><button class="btn" id="import-button" type="submit" style="margin-top:19px">${icon('git')} Import ZIP & analyze ${icon('arrow')}</button></form>`}
 <div class="divider"></div><div class="tag-row"><span class="badge">Correctness risks</span><span class="badge">Dead code candidates</span><span class="badge">Security smells</span><span class="badge">Dependency health</span><span class="badge">Rust rewrite assessment</span></div></section>
 ${guide('How Evolve works',[['Import','Copy source into an isolated, owner-scoped project workspace.'],['Analyze','Run syntax and rule-based checks; preserve file and line evidence.'],['Prioritize','Distinguish verified problems from potential risks and hypotheses.'],['Improve','The next milestone adds test-backed code changes and reviewable PRs.']])}</div>`},
 projects(){return `${pageHeader('YOUR PROJECTS','Everything in one place.','Your created and imported repositories. Only projects you own are visible.')}
 <div class="section-title"><h2>All projects</h2><div class="tag-row"><button class="btn btn-outline" data-page="new">${icon('sparkles')} Start New</button><button class="btn btn-outline" data-page="evolve">${icon('git')} Import</button></div></div><div class="card panel">${projectRows()}</div>`},
 activity(){return `${pageHeader('ENGINEERING ACTIVITY','See the work, not just the result.','Events remain in the workspace even after your browser closes.')}
 <div class="card panel"><h3>Recent activity</h3>${activityRows()}</div><p class="notice" style="margin-top:20px">Background execution requires the separate Oryveta worker. This local preview does not guarantee an always-on cloud worker.</p>`},
 detail(){const p=state.project;if(!p)return `<p>Project unavailable.</p>`;const a=p.analysis;const findings=a?.findings||[];const sourceFiles=p.files||[];return `${pageHeader(p.origin==='import'?'IMPORTED CODEBASE':'GENERATED REPOSITORY',esc(p.name),esc(p.brief))}
 <div class="section-title"><div class="tag-row"><span class="pill">${esc(p.status)}</span><span class="pill">${esc(p.origin==='import'?'Evolve':'Start New')}</span></div><div class="tag-row"><button class="btn btn-outline" data-run-scan="${esc(p.id)}">${icon('refresh')} Analyze</button><button class="btn" data-download="${esc(p.id)}">${icon('download')} Export repository</button></div></div>
 <div class="kpi-grid">${[['Files',sourceFiles.length,'Files in workspace'],['Findings',a?.summary?.findings_count ?? '—','Static analysis only'],['Languages',Object.keys(a?.summary?.language_files||{}).length||'—','Detected file extensions'],['Status',a?'Analyzed':'Pending','Evidence-driven review']].map(k=>`<div class="card kpi"><div class="kpi-label">${k[0]}</div><div class="kpi-val" style="font-size:${String(k[1]).length>10?17:25}px">${esc(k[1])}</div><div class="kpi-meta">${k[2]}</div></div>`).join('')}</div>
 <div class="files-grid"><section class="card panel"><h3>Repository files</h3><div class="code-list">${sourceFiles.length?sourceFiles.map(f=>`<div class="file-line mono">${esc(f)}</div>`).join(''):empty('No files','Project source not found.')}</div></section><section class="card panel"><h3>Engineering next steps</h3><div class="guide-step"><span class="step-no">1</span><div><b>${p.origin==='import'?'Review static findings':'Review your scaffold'}</b><p>${p.origin==='import'?'Potential findings require validation against tests and runtime behavior.':'Your starter is runnable. Business features described in the brief are not yet implemented.'}</p></div></div><div class="guide-step"><span class="step-no">2</span><div><b>Establish regression checks</b><p>Measure existing behavior before modifying code.</p></div></div><div class="guide-step"><span class="step-no">3</span><div><b>Implement verified changes</b><p>Agent-authored fixes, Rust migrations and GitHub PRs are planned integrations, not completed features.</p></div></div></section></div>
 <section class="card panel" style="margin-top:20px"><div class="section-title"><h2>${a?'Static findings':'Analysis status'}</h2>${a?`<span class="pill">${a.summary.findings_count} observations</span>`:''}</div>${a?`<div class="notice">${esc(a.summary.disclaimer)}</div>${findings.length?findings.map(f=>`<div class="finding"><div><b>${esc(f.title)}</b><p>${esc(f.recommendation)}</p><span class="mono">${esc(f.path)}${f.line?':'+f.line:''} · ${esc(f.category)} · confidence: ${esc(f.confidence)}</span></div><span class="pill ${f.severity==='high'?'warning':''}">${esc(f.severity)}</span></div>`).join(''):'<div class="empty">No heuristic findings. This does not mean the code is defect-free.</div>'}`:`<div class="empty">${p.origin==='import'?'Analysis queued. Start the separate background worker to process it.':'No analysis recorded yet. Select Analyze to queue a scan.'}</div>`}</section>`}
};
async function refreshAiStatus(){
 try{
  const [status,budget]=await Promise.all([api('/api/ai/status'),api('/api/ai/budget')]);
  state.modelStatus=status.status;state.modelName=status.model;state.aiBudget=budget;
 }catch{state.modelStatus='offline';state.modelName=null}
 const badge=$('#ai-status');if(badge)badge.textContent=state.modelStatus+(state.modelName?' · '+state.modelName:'');
 const input=$('#ai-prompt');if(input)input.disabled=state.modelStatus!=='ready';
 const button=$('#ai-submit');if(button)button.disabled=state.modelStatus!=='ready';
 const count=$('#ai-budget');if(count&&state.aiBudget)count.textContent=state.aiBudget.remaining_tokens+' tokens left today';
}
async function submitAi(form){
 if(state.preview)throw new Error('Local model inference is not hosted on Vercel');
 const button=$('#ai-submit');button.disabled=true;
 const output=$('#ai-output');output.classList.remove('hidden');output.textContent='Generating with local model…';
 try{
  const result=await api('/api/ai/generate',{method:'POST',data:{prompt:form.elements.prompt.value,max_output_tokens:256}});
  output.textContent=result.text+'\n\nUnverified AI suggestion · '+result.usage.output_tokens+' output tokens';
  state.aiBudget=result.budget;
  const count=$('#ai-budget');if(count)count.textContent=result.budget.remaining_tokens+' tokens left today';
 }catch(e){output.textContent=e.message;toast(e.message,true)}
 finally{button.disabled=state.modelStatus!=='ready'}
}
async function load(){if(state.preview)return;const [projects,overview,activity]=await Promise.all([api('/api/projects'),api('/api/overview'),api('/api/activity')]);state.projects=projects;state.overview=overview;state.activity=activity}
async function navigate(page,projectId){state.current=page;if(page==='detail'){state.project=await api(`/api/projects/${encodeURIComponent(projectId)}`)}if(['home','projects','activity'].includes(page))await load();$('#breadcrumb-current').textContent=titles[page]||page;$('#page').innerHTML=pages[page]?.()||pages.home();document.querySelectorAll('#nav .nav-link').forEach(n=>n.classList.toggle('active',n.dataset.page===(page==='detail'?'projects':page)));document.body.classList.remove('mobile-nav-open');window.scrollTo({top:0,behavior:'instant'});}
async function submitNew(form){if(state.preview)throw new Error('Static preview only — start the local API to create projects');const btn=$('#create-button');btn.disabled=true;try{const result=await api('/api/projects',{method:'POST',data:{name:form.elements.name.value.trim(),brief:form.elements.brief.value.trim(),blueprint:form.elements.blueprint.value}});toast('Starter repository created');await navigate('detail',result.id)}finally{btn.disabled=false}}
async function submitGitHub(){if(state.preview)throw new Error('Static preview only — run the local API to import repositories');const btn=$('#import-button');btn.disabled=true;try{const url=$('#repository-url').value.trim();const result=await api('/api/projects/import/github',{method:'POST',data:{url}});toast('Repository imported. Analysis queued.');await navigate('detail',result.id)}finally{btn.disabled=false}}
async function submitZip(){if(state.preview)throw new Error('Static preview only — run the local API to import repositories');const btn=$('#import-button');btn.disabled=true;try{const file=$('#zip-file').files[0];if(!file||file.size>12*1024*1024)throw new Error('Choose a ZIP smaller than 12 MB');const name=$('#zip-name').value.trim();const result=await api('/api/projects/import/zip',{method:'POST',body:file,headers:{'Content-Type':'application/zip','X-Project-Name':name}});toast('Repository imported. Analysis queued.');await navigate('detail',result.id)}finally{btn.disabled=false}}
async function init(){try{const config=await api('/api/config');if(!config||config.name!=='Oryveta'||typeof config.github_auth_enabled!=='boolean')throw new Error('Hosted API unavailable');if(config.local_demo_enabled)$('#demo-login').classList.remove('hidden');if(!config.github_auth_enabled)$('#github-login').classList.add('hidden');try{state.user=await api('/api/me');state.csrf=state.user.csrf_token;$('#app').classList.remove('hidden');$('#profile-name').textContent=state.user.display_name;$('#avatar').textContent=state.user.display_name[0]?.toUpperCase()||'O';$('#avatar-top').textContent=state.user.display_name[0]?.toUpperCase()||'O';await load();await refreshAiStatus();await navigate('home')}catch(e){$('#login').classList.remove('hidden');if(!config.github_auth_enabled){$('#login-warning').textContent=config.local_demo_enabled?'GitHub OAuth has not been configured. Local demo mode is available.':'GitHub OAuth is not configured. An administrator must set the GitHub OAuth credentials.';$('#login-warning').classList.remove('hidden')}}}catch(e){
 if(window.location.hostname.endsWith('.vercel.app') || new URLSearchParams(window.location.search).get('preview')==='1'){
  state.preview=true;state.user={display_name:'Preview'};state.modelStatus='disabled';
  $('#app').classList.remove('hidden');$('#login').classList.add('hidden');
  $('#profile-name').textContent='Preview';$('#avatar').textContent='P';$('#avatar-top').textContent='P';
  $('#logout').classList.add('hidden');
  await navigate('home');
 }else{$('#login').classList.remove('hidden');toast(e.message,true)}
}}
document.addEventListener('click',async(event)=>{const node=event.target.closest('[data-page],[data-project],[data-tab],[data-download],[data-run-scan],[data-refresh-ai]');if(!node)return;try{if(node.hasAttribute('data-refresh-ai'))await refreshAiStatus();else if(node.dataset.page)await navigate(node.dataset.page);else if(node.dataset.project)await navigate('detail',node.dataset.project);else if(node.dataset.tab){state.importMode=node.dataset.tab;await navigate('evolve')}else if(node.dataset.download){const response=await api(`/api/projects/${encodeURIComponent(node.dataset.download)}/export`);const blob=await response.blob();const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='oryveta-project.zip';document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}else if(node.dataset.runScan){await api(`/api/projects/${encodeURIComponent(node.dataset.runScan)}/analyze`,{method:'POST'});toast('Analysis job queued')}}catch(e){toast(e.message,true)}});
document.addEventListener('submit',async(event)=>{if(!['new-form','github-import','zip-import','ai-form'].includes(event.target.id))return;event.preventDefault();try{if(event.target.id==='ai-form')await submitAi(event.target);else if(event.target.id==='new-form')await submitNew(event.target);else if(event.target.id==='github-import')await submitGitHub();else await submitZip()}catch(e){toast(e.message,true)}});
$('#demo-login').addEventListener('click',async()=>{try{await api('/auth/local-demo',{method:'POST'});window.location.reload()}catch(e){toast(e.message,true)}});
$('#logout').addEventListener('click',async()=>{try{await api('/auth/logout',{method:'POST'});window.location.reload()}catch(e){toast(e.message,true)}});
$('#mobile-menu').addEventListener('click',()=>document.body.classList.toggle('mobile-nav-open'));
init();
