"""Complete *starter repositories*, never represented as fully implemented user briefs."""
from __future__ import annotations

import html
import json
import re
from pathlib import Path

BLUEPRINTS = {
    "web-app": {"name": "Web app", "stack": "Dependency-free HTML / CSS / JavaScript"},
    "python-api": {"name": "Python API", "stack": "FastAPI / SQLite / pytest"},
    "ai-service": {"name": "AI service", "stack": "FastAPI / provider interface / pytest"},
}


def project_slug(name: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")[:60].rstrip("-")
    if not slug:
        raise ValueError("Project name must include letters or digits")
    return slug


def generate_files(name: str, brief: str, blueprint: str) -> dict[str, str]:
    if blueprint not in BLUEPRINTS:
        raise ValueError("Unsupported project template")
    slug = project_slug(name)
    manifest = {
        "name": name, "slug": slug, "brief": brief, "blueprint": blueprint,
        "status": "runnable starter repository",
        "limitations": "Custom business logic requested in the brief is not yet generated",
    }
    files = {
        "README.md": (
            f"# {name}\n\n## Original requirements\n\n{brief}\n\n"
            "## Status\n\nA runnable starter repository generated by Oryveta. "
            "Your requested application-specific logic still requires implementation and verification.\n\n"
            "## Next steps\n\nImplement feature acceptance tests, then application features. "
            "Review dependencies, security and deployment settings before production use.\n"
        ),
        "oryveta.json": json.dumps(manifest, indent=2) + "\n",
        ".gitignore": ".venv/\n__pycache__/\n.pytest_cache/\n*.pyc\n.env\n*.db\n",
        "LICENSE": ("MIT License\n\nCopyright (c) 2026 Oryveta contributors\n\n"
                    "Permission is hereby granted, free of charge, to any person obtaining a copy "
                    "of this software and associated documentation files (the 'Software'), to deal "
                    "in the Software without restriction, including without limitation the rights "
                    "to use, copy, modify, merge, publish, distribute, sublicense, and/or sell "
                    "copies of the Software, and to permit persons to whom the Software is "
                    "furnished to do so, subject to the following conditions:\n\n"
                    "The above copyright notice and this permission notice shall be included "
                    "in all copies or substantial portions of the Software.\n\n"
                    "THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND.\n"),
    }
    if blueprint == "web-app":
        title = html.escape(name, quote=True)
        files.update({
            "index.html": (
                '<!doctype html>\n<html lang="en"><head><meta charset="utf-8">'
                '<meta name="viewport" content="width=device-width, initial-scale=1">'
                f'<title>{title}</title><link rel="stylesheet" href="styles.css"></head>'
                f'<body><header class="header"><strong>{title}</strong></header>'
                '<main class="shell"><span class="eyebrow">Starter application</span>'
                f'<h1>{title}</h1><p>Build your next idea here.</p>'
                '<form id="demo"><label for="task">Your first task</label>'
                '<div class="form-row"><input id="task" placeholder="Add a task" required maxlength="100">'
                '<button type="submit">Add</button></div></form><ul id="tasks"></ul>'
                '</main><script src="app.js" defer></script></body></html>\n'
            ),
            "styles.css": ("*{box-sizing:border-box}body{margin:0;background:#f7f8fa;color:#1e293b;"
                           "font:16px system-ui,sans-serif}.header{background:white;padding:24px 7%;"
                           "border-bottom:1px solid #e2e8f0}.shell{margin:10vh auto;padding:36px;"
                           "background:white;border:1px solid #e2e8f0;border-radius:18px;"
                           "max-width:640px}.eyebrow{color:#6078ad;font-size:12px;"
                           "text-transform:uppercase;letter-spacing:2px}h1{margin-bottom:8px}"
                           "p{color:#64748b}label{display:block;margin:26px 0 8px}.form-row{display:flex;"
                           "gap:8px}input{flex:1;padding:11px;border:1px solid #cbd5e1;"
                           "border-radius:8px}button{background:#4b69b5;color:white;border:0;"
                           "border-radius:8px;padding:11px 18px;cursor:pointer}li{padding:8px}"),
            "app.js": (
                "const form = document.querySelector('#demo');\n"
                "const tasks = document.querySelector('#tasks');\n"
                "form.addEventListener('submit', (event) => {\n"
                "  event.preventDefault();\n"
                "  const input = document.querySelector('#task');\n"
                "  const item = document.createElement('li');\n"
                "  item.textContent = input.value;\n"
                "  tasks.append(item);\n"
                "  form.reset();\n"
                "});\n"
            ),
            "tests/test_project.py": (
                "import unittest\nfrom pathlib import Path\n\n"
                "class TestAssets(unittest.TestCase):\n"
                "    def test_assets_are_present(self):\n"
                "        root = Path(__file__).resolve().parents[1]\n"
                "        for name in ('index.html', 'app.js', 'styles.css'):\n"
                "            self.assertTrue((root / name).is_file())\n"
            ),
            ".github/workflows/ci.yml": (
                "name: CI\non: [push, pull_request]\njobs:\n  smoke:\n    runs-on: ubuntu-latest\n"
                "    steps:\n      - uses: actions/checkout@v4\n"
                "      - run: python -m unittest discover -s tests -p 'test_*.py'\n"
            ),
        })
        files["README.md"] += "\n## Run locally\n\n`python -m http.server 8000`, then open http://localhost:8000.\n"
    else:
        files.update({
            "app/__init__.py": "",
            "app/main.py": (
                '"""Runnable starter service."""\n'
                "from fastapi import FastAPI\nfrom pydantic import BaseModel, Field\n\n"
                f"app = FastAPI(title={name!r})\n\n"
                "class Item(BaseModel):\n    name: str = Field(min_length=1, max_length=120)\n\n"
                "@app.get('/health')\ndef health():\n    return {'status': 'ok'}\n\n"
                "@app.post('/items')\ndef create_item(item: Item):\n"
                "    return {'created': True, 'item': item.model_dump()}\n"
            ),
            "requirements.txt": "fastapi>=0.110,<1\nuvicorn>=0.29,<1\npytest>=8,<10\nhttpx>=0.27,<1\n",
            "pyproject.toml": "[tool.pytest.ini_options]\npythonpath = ['.']\ntestpaths = ['tests']\n",
            "tests/test_api.py": (
                "from fastapi.testclient import TestClient\nfrom app.main import app\n\n"
                "client = TestClient(app)\n\n"
                "def test_health():\n    assert client.get('/health').json() == {'status': 'ok'}\n\n"
                "def test_item_validation():\n    assert client.post('/items', json={'name': ''}).status_code == 422\n"
            ),
            "Dockerfile": (
                "FROM python:3.12-slim\nWORKDIR /service\n"
                "COPY requirements.txt .\nRUN pip install --no-cache-dir -r requirements.txt\n"
                "COPY app ./app\nUSER 65532\nEXPOSE 8000\n"
                'CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]\n'
            ),
            ".github/workflows/ci.yml": (
                "name: CI\non: [push, pull_request]\njobs:\n  test:\n    runs-on: ubuntu-latest\n"
                "    steps:\n      - uses: actions/checkout@v4\n"
                "      - uses: actions/setup-python@v5\n        with:\n          python-version: '3.12'\n"
                "      - run: pip install -r requirements.txt\n      - run: pytest -q\n"
            ),
        })
        if blueprint == "ai-service":
            files["app/provider.py"] = (
                '"""Open-model adapter, deliberately requires explicit local configuration."""\n'
                "from dataclasses import dataclass\n\n"
                "@dataclass\nclass GenerationRequest:\n    prompt: str\n\n"
                "class InferenceNotConfigured(RuntimeError):\n    pass\n\n"
                "def generate(request: GenerationRequest) -> str:\n"
                "    raise InferenceNotConfigured('Configure an approved local model before inference')\n"
            )
        files["README.md"] += (
            "\n## Run locally\n\n"
            "`pip install -r requirements.txt` then "
            "`uvicorn app.main:app --reload`. Run `pytest -q` to verify the starter.\n"
        )
    return files


def write_scaffold(root: Path, files: dict[str, str]) -> None:
    root = root.resolve()
    root.mkdir(parents=True, exist_ok=False)
    for relative, content in files.items():
        out = (root / relative).resolve()
        if not out.is_relative_to(root):
            raise ValueError("Unsafe output path")
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(content, encoding="utf-8")
